const Data = [
  {
    id: 1,
    title: "Web Application Development",
    code: "CSSE3143",
    teacher: "Asad Kamal",
    credits: 3,
    grade: "A",
    attendance: 93,
    status: "Active",
    totalScore: 90,
    totalMarks: 100,
    percentage: 90,
    assessments: [
      { type: "Class Participation", obtained: 9, total: 10 },
      { type: "Assignment", obtained: 8, total: 10 },
      { type: "Quiz", obtained: 19, total: 20 },
      { type: "Mids", obtained: 18, total: 20 },
      { type: "Final", obtained: 36, total: 40 },
    ],
  },
  {
    id: 2,
    title: "Operating Systems - Lab",
    code: "CSCS3551",
    teacher: "Qaisar Aslam",
    credits: 1,
    grade: "B+",
    attendance: 85,
    status: "Active",
    totalScore: 82,
    totalMarks: 100,
    percentage: 82,
    assessments: [
      { type: "Class Participation", obtained: 8, total: 10 },
      { type: "Assignment", obtained: 7, total: 10 },
      { type: "Quiz", obtained: 16, total: 20 },
      { type: "Mids", obtained: 17, total: 20 },
      { type: "Final", obtained: 34, total: 40 },
    ],
  },
  {
    id: 3,
    title: "Introduction to Software Engineering",
    code: "CSSE3113",
    teacher: "Muhammad Basit Ali Gillani",
    credits: 3,
    grade: "B",
    attendance: 77,
    status: "Active",
    totalScore: 73,
    totalMarks: 100,
    percentage: 73,
    assessments: [
      { type: "Class Participation", obtained: 7, total: 10 },
      { type: "Assignment", obtained: 6, total: 10 },
      { type: "Quiz", obtained: 15, total: 20 },
      { type: "Mids", obtained: 14, total: 20 },
      { type: "Final", obtained: 31, total: 40 },
    ],
  },
  {
    id: 4,
    title: "Operating Systems",
    code: "CSCS3553",
    teacher: "Dr Adnan Ghafoor",
    credits: 3,
    grade: "B-",
    attendance: 71,
    status: "Active",
    totalScore: 68,
    totalMarks: 100,
    percentage: 68,
    assessments: [
      { type: "Class Participation", obtained: 6, total: 10 },
      { type: "Assignment", obtained: 5, total: 10 },
      { type: "Quiz", obtained: 13, total: 20 },
      { type: "Mids", obtained: 12, total: 20 },
      { type: "Final", obtained: 32, total: 40 },
    ],
  },
  {
    id: 5,
    title: "Database Systems",
    code: "CSSE3212",
    teacher: "Hina Rauf",
    credits: 3,
    grade: "A-",
    attendance: 89,
    status: "Active",
    totalScore: 85,
    totalMarks: 100,
    percentage: 85,
    assessments: [
      { type: "Class Participation", obtained: 9, total: 10 },
      { type: "Assignment", obtained: 7, total: 10 },
      { type: "Quiz", obtained: 17, total: 20 },
      { type: "Mids", obtained: 16, total: 20 },
      { type: "Final", obtained: 36, total: 40 },
    ],
  },
  {
    id: 6,
    title: "Computer Networks",
    code: "CSCS3421",
    teacher: "Imran Latif",
    credits: 3,
    grade: "C+",
    attendance: 80,
    status: "Active",
    totalScore: 61,
    totalMarks: 100,
    percentage: 61,
    assessments: [
      { type: "Class Participation", obtained: 6, total: 10 },
      { type: "Assignment", obtained: 5, total: 10 },
      { type: "Quiz", obtained: 12, total: 20 },
      { type: "Mids", obtained: 13, total: 20 },
      { type: "Final", obtained: 25, total: 40 },
    ],
  },
];

export default Data;
